services:
  experiment-executor:
    restart: unless-stopped
    healthcheck:
      test: >
        curl -f -X GET http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    build:
      context: .
      dockerfile: Dockerfile