spring:
  application:
    name: experiment-executor
  data:
    redis:
      password: "redis"
server:
  port: 8888

grafana:
  api-token: ${GRAFANA_API_TOKEN}
  url:  "http://localhost:3001"
pushgateway:
  url: "localhost:9091"
influxdb:
  url: "http://localhost:8086/api/v2/write?org=misarch&bucket=gatling&precision=ms"
misarch:
  experiment-config:
    host: "http://localhost:3000"
chaostoolkit:
  executor-host: "http://localhost:8890"
gatling:
  target-endpoint: "http://gateway:8080"
  executor-host: "http://localhost:8889"
  token:
    host: "http://localhost:8081"
    client-id: "frontend"
    path: "/keycloak/realms/Misarch/protocol/openid-connect/token"
    username: "eliasmueller"
    password: "123"
experiment-executor:
  url: "http://192.168.178.155:8888"
  base-path: "/Users/p371728/master/thesis/misarch/tests"
  template-path: "src/main/resources/templates"
  trigger-delay: 40000
  cors-origins:
    - "http://localhost:5173"