spring:
  application:
    name: experiment-executor
server:
  port: 8888

grafana:
  url:  ${GRAFANA_HOST}
  admin-user: ${GRAFANA_ADMIN_USER}
  admin-password: ${GRAFANA_ADMIN_PASSWORD}
influxdb:
  url: ${INFLUXDB_URL}
  token: ${INFLUXDB_TOKEN}
misarch:
  experiment-config:
    active: ${USE_MISARCH_EXPERIMENT_CONFIG}
    host: ${MISARCH_EXPERIMENT_CONFIG_HOST}
chaostoolkit:
  executor-host: ${CHAOSTOOLKIT_EXECUTOR_HOST}
gatling:
  executor-host: ${GATLING_EXECUTOR_HOST}
experiment-executor:
  base-path: "/home/java/tests"
  url: ${EXPERIMENT_EXECUTOR_URL}
  template-path: "src/main/resources/templates"
  store-result-data-in-files: ${STORE_RESULT_DATA_IN_FILES}
  cors-origins:
    - "http://localhost:5173"