spring:
  application:
    name: experiment-executor
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: 6379
server:
  port: 8888

grafana:
  api-token: ${GRAFANA_API_TOKEN}
  url:  ${GRAFANA_HOST}
pushgateway:
  url: ${PUSHGATEWAY_HOST}
influxdb:
  url: ${INFLUXDB_URL}
misarch:
  experiment-config:
    host: ${MISARCH_EXPERIMENT_CONFIG_HOST}
chaostoolkit:
  executor-host: ${CHAOSTOOLKIT_EXECUTOR_HOST}
gatling:
  target-endpoint: ${GATLING_TARGET_ENDPOINT}
  executor-host: ${GATLING_EXECUTOR_HOST}
  token:
    host: ${GATLING_TOKEN_HOST}
    path: ${GATLING_TOKEN_PATH}
    client-id: ${GATLING_TOKEN_CLIENT_ID}
    username: ${GATLING_TOKEN_USERNAME}
    password: ${GATLING_TOKEN_PASSWORD}
experiment-executor:
  base-path: "/home/java"
  template-path: "src/main/resources/templates"
  trigger-delay: ${EXPERIMENT_TRIGGER_DELAY}
  cors-origins:
    - "http://localhost:5173"