{
 "title": "Experiment Dashboard REPLACE_ME_TEST_UUID REPLACE_ME_TEST_VERSION",
 "time": { "from": "REPLACE_ME_TEST_START_TIME", "to": "REPLACE_ME_TEST_END_TIME" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "address, catalog, discount, gateway, inventory, invoice, media, notification, order, payment, return, review, shipment, shoppingcart, simulation, tax, user, wishlist"
   },
   {
    "name": "testUUID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"gatling\",\n  tag: \"testUUID\",\n  start: -5d\n)"
    }
   },
   {
    "name": "gatling_request",
    "label": "gatling request",
    "query": "createordermuta, createshoppingc, placeordermuta, product, products, shipmentmethods, users, paymentinformat"
   },
   {
    "name": "testVersion",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"gatling\",\n  tag: \"testVersion\",\n  start: -5d\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gatling total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"activeUsers\")\n  |> filter(fn: (r) => r.scenario == \"BuyProcess\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "number reqs with resp. time t < 800 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group1Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "number reqs with resp. time 800 ms <  t < 1200 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group2Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "number reqs with resp. time t > 1200 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group3Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "number failed requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group4Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"responses\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n"
    }
   ]
  },
  {
   "title": "mean requests/sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanNumberOfRequestsPerSecondTotal\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean requests/sec ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanNumberOfRequestsPerSecondOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean requests/sec ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanNumberOfRequestsPerSecondKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "min response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "max response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "min response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "max response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "min response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "max response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "gatling request: ${gatling_request}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "number of requests total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsTotal_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "min response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "max response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "number of requests ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "min response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "max response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "number of requests ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "min response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "mean response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "max response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  { "title": "${service} service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "service" },
  {
   "title": "${service} CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"infrastructure-docker-${service}-1\"}[20s])",
     "legendFormat": "vCPUs"
    }
   ]
  },
  {
   "title": "${service} dapr http server latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dapr_http_server_latency_sum{app_id=\"${service}\"}[20s])",
     "legendFormat": "Path: {{path}}, Status Code: {{status}}"
    }
   ]
  },
  {
   "title": "${service} memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name=\"infrastructure-docker-${service}-1\"} or on() vector(0)) / 1073741824",
     "legendFormat": "memory in GB"
    }
   ]
  },
  {
   "title": "${service} http server errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_count{exported_job=\"${service}\", http_response_status_code!=\"200\", http_response_status_code!=\"201\"}[20s])",
     "legendFormat": "Path: {{http_route}}, Response Code: {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "${service} container instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 41 },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"infrastructure-docker-${service}-1\"}) or on() vector(0)\n",
     "legendFormat": "container instances"
    }
   ]
  },
  {
   "title": "${service} dapr pubsub egress latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dapr_component_pubsub_egress_latencies_sum{app_id=\"${service}\"}[20s])",
     "legendFormat": "Topic: {{topic}}, Success: {{success}}"
    }
   ]
  },
  {
   "title": "${service} server http request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_sum{exported_job=\"${service}\", http_route!=\"/health\", http_route!=\"/**\", http_route!=\"/dapr/config\", http_route!=\"/dapr/subscribe\"}[20s])",
     "legendFormat": "Path: {{http_route}}"
    }
   ]
  },
  {
   "title": "${service} dapr http client roundtrip latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dapr_http_client_roundtrip_latency_sum{app_id=\"${service}\", path!=\"/_ecs/variables-event\", path!=\"_ecs/defined-variables\", path!=\"/dapr/config\"}[20s])",
     "legendFormat": "Path: {{path}}"
    }
   ]
  },
  {
   "title": "${service} dapr http completed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(dapr_http_client_completed_count{app_id=\"${service}\", path!=\"/_ecs/variables-event\", path!=\"_ecs/defined-variables\", path!=\"/dapr/config\"}[20s])",
     "legendFormat": "Path: {{path}}, Status: {{status}}"
    }
   ]
  }
 ]
}