{
 "title": "Experiment Dashboard REPLACE_ME_TEST_UUID REPLACE_ME_TEST_VERSION",
 "time": { "from": "REPLACE_ME_TEST_START_TIME", "to": "REPLACE_ME_TEST_END_TIME" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "address, catalog, discount, gateway, inventory, invoice, media, notification, order, payment, return, review, shipment, shoppingcart, simulation, tax, user, wishlist"
   },
   {
    "name": "testUUID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"gatling\",\n  tag: \"testUUID\",\n  start: -5d\n)"
    }
   },
   {
    "name": "gatling_request",
    "label": "gatling request",
    "query": "createordermuta, createshoppingc, placeordermutat, product, products, shipmentmethods, users, paymentinformat"
   },
   {
    "name": "testVersion",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"gatling\",\n  tag: \"testVersion\",\n  start: -5d\n)"
    }
   },
   { "name": "timeShift" }
  ]
 },
 "panels": [
  { "title": "gatling total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"activeUsers\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      label: r.scenario + \" (Now)\"\n  }))\n  |> group(columns: [\"label\"])"
    },
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"activeUsers\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> timeShift(duration: ${timeShift})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      label: r.scenario + \" (${timeShift} ago)\"\n  }))\n  |> group(columns: [\"label\"])"
    }
   ]
  },
  {
   "title": "number reqs with resp. time t < 800 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group1Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group1Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "percentage reqs with resp. time t < 800 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group1Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group1Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "number reqs with resp. time 800 ms < t < 1200 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group2Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group2Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "percentage reqs with resp. time 800 ms < t < 1200 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group2Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group2Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "number reqs with resp. time t > 1200 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group3Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group3Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "percentage reqs with resp. time t > 1200 ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group3Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group3Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "number failed requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group4Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group4Count\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "percentage failed requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group4Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"group4Percentage\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"responses\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      label: r.flavor + \" (Now)\"\n  }))\n  |> group(columns: [\"label\"])"
    },
    {
     "query": "from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"responses\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> timeShift(duration: ${timeShift})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      label: r.flavor + \" (${timeShift} ago)\"\n  }))\n  |> group(columns: [\"label\"])"
    }
   ]
  },
  {
   "title": "mean requests/sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanNumberOfRequestsPerSecondTotal\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanNumberOfRequestsPerSecondTotal\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "percentage mean requests/sec ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentageMeanNumberOfRequestsPerSecondOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentageMeanNumberOfRequestsPerSecondOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "percentage mean requests/sec ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentageMeanNumberOfRequestsPerSecondKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentageMeanNumberOfRequestsPerSecondKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "min response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "mean response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "max response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTime\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "min response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "mean response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "max response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeOk\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "min response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "mean response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "max response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeKo\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "50th percentile response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles1\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles1\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "75th percentile response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles2\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles2\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "95th percentile response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles3\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles3\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "99th percentile response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles4\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles4\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "50th percentile response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles1Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles1Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "75th percentile response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles2Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles2Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "95th percentile response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles3Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles3Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "99th percentile response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles4Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles4Ok\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "50th percentile response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles1Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles1Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "75th percentile response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles2Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles2Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "95th percentile response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles3Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles3Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "99th percentile response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles4Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"percentiles4Ko\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  { "title": "gatling errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 1, "y": 24 }, "options": { "content": "REPLACE_ME_GATLING_ERRORS" } },
  {
   "title": "gatling request: ${gatling_request}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "number of requests total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsTotal_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsTotal_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "min response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "mean response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "max response time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTime_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "number of requests ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "min response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "mean response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "max response time ok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeOk_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "number of requests ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"numberOfRequestsKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "min response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"minResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "mean response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"meanResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  {
   "title": "max response time ko",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\")\n  |> aggregateWindow(every: 1m, fn: last)\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"Now\" }))\n\nshifted = from(bucket: \"gatling\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"maxResponseTimeKo_${gatling_request}\")\n  |> filter(fn: (r) => r.testUUID == \"${testUUID}\")\n  |> filter(fn: (r) => r.testVersion == \"${testVersion}\") \n  |> timeShift(duration: ${timeShift})\n  |> aggregateWindow(every: 1m, fn: first)\n  |> first()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, label: \"${timeShift} ago\" }))\n\nunion(tables: [current, shifted])\n  |> group(columns: [\"label\"])\n"
    }
   ]
  },
  { "title": "${service} service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }, "repeat": "service" },
  {
   "title": "${service} container instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 40 },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{container=\"misarch-${service}\"}) or on() vector(0)",
     "legendFormat": "container instances"
    },
    {
     "expr": "count(container_start_time_seconds{container=\"misarch-${service}\"} offset ${timeShift}) or on() vector(0)",
     "legendFormat": "container instances (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"misarch-${service}\"}[20s])",
     "legendFormat": "vCPUs"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"misarch-${service}\"}[20s] offset ${timeShift})",
     "legendFormat": "vCPUs (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} dapr http server latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dapr_http_server_latency_sum{app_id=\"${service}\"}[20s])",
     "legendFormat": "Path: {{path}}, Status Code: {{status}}"
    },
    {
     "expr": "rate(dapr_http_server_latency_sum{app_id=\"${service}\"}[20s] offset ${timeShift})",
     "legendFormat": "Path: {{path}}, Status Code: {{status}} (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container=\"misarch-${service}\"} or on() vector(0)) / 1073741824",
     "legendFormat": "memory in GB"
    },
    {
     "expr": "(container_memory_usage_bytes{container=\"misarch-${service}\"} offset ${timeShift} or on() vector(0)) / 1073741824",
     "legendFormat": "memory in GB (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} dapr http completed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 56 },
   "targets": [
    {
     "expr": "rate(dapr_http_client_completed_count_total{app_id=\"${service}\", path!=\"/_ecs/variables-event\", path!=\"_ecs/defined-variables\", path!=\"/dapr/config\"}[20s])",
     "legendFormat": "Path: {{path}}, Status: {{status}}"
    },
    {
     "expr": "rate(dapr_http_client_completed_count_total{app_id=\"${service}\", path!=\"/_ecs/variables-event\", path!=\"_ecs/defined-variables\", path!=\"/dapr/config\"}[20s] offset ${timeShift})",
     "legendFormat": "Path: {{path}}, Status: {{status}} (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} http server active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "http_server_active_requests{exported_job=\"${service}\"}",
     "legendFormat": "HTTP {{http_request_method}}"
    },
    {
     "expr": "http_server_active_requests{exported_job=\"${service}\"} offset ${timeShift}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${service} dapr http client roundtrip latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dapr_http_client_roundtrip_latency_sum{app_id=\"${service}\", path!=\"/_ecs/variables-event\", path!=\"_ecs/defined-variables\", path!=\"/dapr/config\"}[20s])",
     "legendFormat": "Path: {{path}}"
    },
    {
     "expr": "rate(dapr_http_client_roundtrip_latency_sum{app_id=\"${service}\", path!=\"/_ecs/variables-event\", path!=\"_ecs/defined-variables\", path!=\"/dapr/config\"}[20s] offset ${timeShift})",
     "legendFormat": "Path: {{path}} (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} http server errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{exported_job=\"${service}\", http_response_status_code!=\"200\", http_response_status_code!=\"201\"}[20s])",
     "legendFormat": "Path: {{http_route}}, Response Code: {{http_response_status_code}}"
    },
    {
     "expr": "rate(http_server_request_duration_seconds_count{exported_job=\"${service}\", http_response_status_code!=\"200\", http_response_status_code!=\"201\"}[20s] offset ${timeShift})",
     "legendFormat": "Path: {{http_route}}, Response Code: {{http_response_status_code}} (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} dapr pubsub egress latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dapr_component_pubsub_egress_latencies_sum{app_id=\"${service}\"}[20s])",
     "legendFormat": "Topic: {{topic}}, Success: {{success}}"
    },
    {
     "expr": "rate(dapr_component_pubsub_egress_latencies_sum{app_id=\"${service}\"}[20s] offset ${timeShift})",
     "legendFormat": "Topic: {{topic}}, Success: {{success}} (${timeShift} ago)"
    }
   ]
  },
  {
   "title": "${service} server http request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum{exported_job=\"${service}\", http_route!=\"/health\", http_route!=\"/**\", http_route!=\"/dapr/config\", http_route!=\"/dapr/subscribe\"}[20s])",
     "legendFormat": "Path: {{http_route}}"
    },
    {
     "expr": "rate(http_server_request_duration_seconds_sum{exported_job=\"${service}\", http_route!=\"/health\", http_route!=\"/**\", http_route!=\"/dapr/config\", http_route!=\"/dapr/subscribe\"}[20s] offset ${timeShift})",
     "legendFormat": "Path: {{http_route}} (${timeShift} ago)"
    }
   ]
  }
 ]
}